### ISSUE TITLE
Is Visual Studio 2012 Premium supported?

### ISSUE THREAD

**Issue by NKJo28** [jsargiot/visual-coverage#19]
Hi, i'm currently exploring a few tools to use for code coverage, and one important aspect is the ability to convert the coverage file to Clover format. 

So just a simple question, VS 2015 Enterprise is listed as a requirement but is this fixed and can VS 2012 Premium be used as an alternative? I'd like to know before committing and getting stuck.

**Comment by jsargiot** [comment]
Hi @NKJo28, only Enterprise editions come with code coverage tools [1], I'm not sure if premium is similar. visual-coverage relies on the visual studio libs being present, you can check whether these libs are available in your system: `Microsoft.VisualStudio.Coverage.Analysis.dll` and `Microsoft.VisualStudio.Coverage.Interop.dll`, if they are there, you can run visual-coverage.

[1]: https://www.visualstudio.com/vs/compare/

**Comment by NKJo28** [comment]
Thanks @jsargiot , it seems that "Premium 2012" is a cross between the Professional and Ultimate editions. MS removed it and Ultimate but replaced them with "Enterprise", it does include code coverage functionality.

Either way, really appreciate you providing the specific required DLL's, they are present in the Premium edition. Perhaps you could add those to the readme in case someone else stumbles upon your tool with another weird edition of Visual Studio.
