### ISSUE TITLE
Not able to find Microsoft.VisualStudio.Coverage.Analysis and interop

### ISSUE THREAD

**Issue by mkbansal145** [jsargiot/visual-coverage#21]

**Comment by mkbansal145** [comment]
Hi Team,

Where can get the dlls for Microsoft.VisualStudio.Coverage.Analysis and interop to be referenced in the visual coverage project

**Comment by jsargiot** [comment]
Hey @mkbansal145, which version of Visual Studio do you have? Check this comment: https://github.com/jsargiot/visual-coverage/issues/19#issuecomment-301575362. Only Enterprise version contains the required dlls.

**Comment by mkbansal145** [comment]
Hi I am using Enterprise edition only but these dlls are no where to be found. I even reinstalled my enterprise edition of VS 2017 again to check.

**Comment by jsargiot** [comment]
I have that version and I can find the assemblies in: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.Coverage.Analysis.dll

If you can't find them there, check that when you install VS you check the Code Coverage package.
